version: '3.7'

services:

  schemacrawler:
    image: schemacrawler/schemacrawler
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./_testdb
        target: /home/schcrwlr/_testdb
