name: Create Icons

on:
  workflow_dispatch:
  push:
    paths:
      - '**/schemacrawler_logo.svg'

permissions: read-all

jobs:
  build:
    name: Create Icons
    runs-on: ubuntu-latest
    steps:

# CHECKOUT CODE
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v3

# CREATE ICONS
    - id: create-icons
      name: Create icons for different platforms
      run: |
        # Create icons for different platforms
        convert -version
        # Create 180 pixel icon
        convert \
          -background transparent \
          -density 1000 \
          -resize 150x150 \
          -border 30 \
          -bordercolor transparent \
          ./schemacrawler-website/src/site/resources/images/schemacrawler_logo.svg \
          ./schemacrawler-website/src/site/resources/images/schemacrawler_logo.png
        # Create ico icon
        convert \
          -background transparent \
          -density 256x256 \
          -define icon:auto-resize \
          -colors 256 \
          ./schemacrawler-website/src/site/resources/images/schemacrawler_logo.svg \
          ./schemacrawler-website/src/site/resources/images/schemacrawler_logo.ico
        # Create left-aligned 16:9 banner in two steps
        convert \
          -background transparent \
          -density 1000 \
          -resize 450x450 \
          -border 100 \
          -bordercolor transparent \
          ./schemacrawler-website/src/site/resources/images/schemacrawler_logo.svg \
          ./schemacrawler-website/src/site/resources/images/schemacrawler_banner.png
        convert \
          -background transparent \
          -density 1000 \
          -extent 1200x675 \
          -gravity west \
          -bordercolor transparent \
          ./schemacrawler-website/src/site/resources/images/schemacrawler_banner.png \
          ./schemacrawler-website/src/site/resources/images/schemacrawler_banner.png

# UPLOAD ICONS
    - id: upload-icons
      name: Upload generated icons
      uses: actions/upload-artifact@v3
      with:
        name: icons
        path: ./schemacrawler-website/src/site/resources/images/schemacrawler_*.*
        retention-days: 5
