name: Integration Tests

on: [push]

jobs:
  build:
    name: Build, test, and publish results
    runs-on: ubuntu-latest
    steps:
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - id: install-packages
      name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install graphviz -qq
    - id: show-environment
      name: Show environment
      run: |
        echo github.repository: ${{ github.repository }}
        echo github.ref: ${{ github.head_ref || github.ref }}
        echo github.sha: ${{ github.sha }}
        mvn -v
    - id: build-test
      name: Build and run integration tests
      env:
        TZ: GMT
      run: |
        mvn \
          --no-transfer-progress \
          --batch-mode \
          -Dtestcoverage \
          -Dlightdb \
          -Dheavydb \
          clean install \
          org.jacoco:jacoco-maven-plugin:0.8.5:report-aggregate
    - id: publish-results
      name: Upload results and coverage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        bash <(curl -s https://codecov.io/bash) -t 4456b669-238d-485f-a64a-250449710514
