name: Mutation Tests

on:
  schedule:
    - cron: '10 0 1,11,21 * *'

jobs:
  build:
    name: Build, run mutation tests, and publish results
    runs-on: ubuntu-latest
    steps:

# SETUP BUILD ENVIRONMENT
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@latest
    - id: setup-jdk
      name: Set up JDK
      uses: actions/setup-java@latest
      with:
        java-version: 8
    - id: install-packages
      name: Install packages
      run: |
        sudo apt-get -qq update
        sudo apt-get -q install graphviz
    - id: show-environment
      name: Show environment
      run: |
        echo github.repository: ${{ github.repository }}
        echo github.ref: ${{ github.head_ref || github.ref }}
        echo github.sha: ${{ github.sha }}
        mvn -v
        cat ~/.m2/settings.xml

# BUILD AND TEST
    - id: build-test
      name: Build and run mutation tests
      run: |
        mvn \
          --no-transfer-progress \
          --batch-mode \
          package \
          org.pitest:pitest-maven:mutationCoverage

# GET TEST RESULTS
    - id: upload-test-results
      name: Upload mutation test results
      uses: actions/upload-artifact@v1
      with:
        name: mutation-test-results
        path: ./schemacrawler-api/target/pit-reports
